src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity=Chaton::class, mappedBy="Categorie", orphanRemoval=true)
     */
    private $chatons;

    public function __construct()
    {
        $this->chatons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Chaton>
     */
    public function getChatons(): Collection
    {
        return $this->chatons;
    }

    public function addChaton(Chaton $chaton): self
    {
        if (!$this->chatons->contains($chaton)) {
            $this->chatons[] = $chaton;
            $chaton->setCategorie($this);
        }

        return $this;
    }

    public function removeChaton(Chaton $chaton): self
    {
        if ($this->chatons->removeElement($chaton)) {
            // set the owning side to null (unless already changed)
            if ($chaton->getCategorie() === $this) {
                $chaton->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Controller/CategoriesController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieSupprimerType;
use App\Form\CategorieType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoriesController extends AbstractController
{
    /**
     * @Route("/", name="app_categories")
     */
    public function index(ManagerRegistry $doctrine): Response
    {

        //On va aller chercher les catégories dans la BDD
        //pour ça on a besoin d'un repository
        $repo = $doctrine->getRepository(Categorie::class);
        $categories=$repo->findAll(); //select * transformé en liste de Categorie

        return $this->render('categories/index.html.twig', [
            'categories'=>$categories
        ]);
    }

    /**
     * @Route("/categorie/ajouter", name="app_categories_ajouter")
     */
    public function ajouter(ManagerRegistry $doctrine, Request $request): Response
    {
        //créer le formulaire
        //on crée d'abord une catégorie vide
        $categorie=new Categorie();
        //à partir de ça je crée le formulaire
        $form=$this->createForm(CategorieType::class, $categorie);

        //On gère le retour du formulaire tout de suite
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //on va utiliser l'entity manager de doctrine
            $em=$doctrine->getManager();
            //on lui dit qu'on veut mettre la catégorie dans la table
            $em->persist($categorie);

            //on génère l'appel SQL (l'insert ici)
            $em->flush();

            //on revient à l'accueil
            return $this->redirectToRoute("app_categories");
        }

        return $this->render("categories/ajouter.html.twig",[
           "formulaire"=>$form->createView()
        ]);
    }

    /**
     * @Route("/categorie/modifier/{id}", name="app_categories_modifier")
     */
    public function modifier($id, ManagerRegistry $doctrine, Request $request): Response{
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec une catégorie existante
        $categorie = $doctrine->getRepository(Categorie::class)->find($id);

        //je vais gérer le fait que l'id n'existe pas
        if (!$categorie){
            throw $this->createNotFoundException("Pas de catégorie avec l'id $id");
        }

        //Si j'arrive là c'est qu'elle existe en BDD
        //à partir de ça je crée le formulaire
        $form=$this->createForm(CategorieType::class, $categorie);

        //On gère le retour du formulaire tout de suite
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //on va utiliser l'entity manager de doctrine
            $em=$doctrine->getManager();
            //on lui dit qu'on veut mettre la catégorie dans la table
            $em->persist($categorie);

            //on génère l'appel SQL (update ici)
            $em->flush();

            //on revient à l'accueil
            return $this->redirectToRoute("app_categories");
        }

        return $this->render("categories/modifier.html.twig",[
            "categorie"=>$categorie,
            "formulaire"=>$form->createView()
        ]);
    }

    /**
     * @Route("/categorie/supprimer/{id}", name="app_categories_supprimer")
     */
    public function supprimer($id, ManagerRegistry $doctrine, Request $request): Response{
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec une catégorie existante
        $categorie = $doctrine->getRepository(Categorie::class)->find($id);

        //je vais gérer le fait que l'id n'existe pas
        if (!$categorie){
            throw $this->createNotFoundException("Pas de catégorie avec l'id $id");
        }

        //Si j'arrive là c'est qu'elle existe en BDD
        //à partir de ça je crée le formulaire
        $form=$this->createForm(CategorieSupprimerType::class, $categorie);

        //On gère le retour du formulaire tout de suite
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //on va utiliser l'entity manager de doctrine
            $em=$doctrine->getManager();
            //on lui dit qu'on supprimer la catégorie
            $em->remove($categorie);

            //on génère l'appel SQL (update ici)
            $em->flush();

            //on revient à l'accueil
            return $this->redirectToRoute("app_categories");
        }

        return $this->render("categories/supprimer.html.twig",[
            "categorie"=>$categorie,
            "formulaire"=>$form->createView()
        ]);
    }
}

templates/categories/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une catégorie{% endblock %}

{% block body %}
    <h1>Ajouter une catégorie</h1>
    {{ form(formulaire) }}
{% endblock %}

templates/categories/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des chatons en BDD{% endblock %}

{% block body %}
    <h1>Gestion des chatons en BDD</h1>
    <table class="table table-striped">
        <tr>
            <th>Titre</th>
            <th>Description</th>
            <th></th>
        </tr>
        {% for c in categories %}
            <tr>
                <td>{{ c.titre }}</td>
                <td>{{ c.description }}</td>
                <td>
                    <a href="{{ path("app_categories_modifier", {"id": c.id}) }}" class="btn btn-primary">modifier</a>
                    <a href="{{ path("app_categories_supprimer", {"id": c.id}) }}" class="btn btn-danger">supprimer</a>
                    <a href="{{path("app_chatons_voir",{"idCategorie":c.id})}}" class="btn btn-warning">chatons</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{path("app_categories_ajouter")}}" class="btn btn-success">Ajouter une catégorie</a>
{% endblock %}

templates/categories/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une catégorie{% endblock %}

{% block body %}
    <h1>Modifier la catégorie <i>{{ categorie.titre }}</i></h1>
    {{ form(formulaire) }}
{% endblock %}

templates/categories/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer une catégorie{% endblock %}

{% block body %}
    <h1>Supprimer la catégorie <i>{{ categorie.titre }} ?</i></h1>
    {{ form(formulaire) }}
    {#je vais mettre un petit bouton retour...#}
    <a href="{{ path("app_categories") }}" class="btn btn-default">Retour</a>
{% endblock %}